### ISSUE TITLE
Πολύ μεγάλα λογότυπα

### ISSUE THREAD

**Issue by billniakas** [JohnGavr/askfetch#2]
Εμφανίζονται πολύ μεγάλα τα λογότυπα των διανομών. Σε αντίθεση με άλλα προγράμματα, το λογότυπο είναι αρκετά μεγάλο και λίγες οι απεικονιζόμενες πληροφορίες.

![Στιγμιότυπο από 2019-07-15 12-51-16](https://user-images.githubusercontent.com/12209936/61208249-9cdb4d80-a6ff-11e9-9614-acac32596594.png)

**Comment by arvchristos** [comment]
Έχεις δίκιο ως προς το μέγεθος, αν και εκτός του default tux (που φαίνεται στο screenshot σου) είναι
ισομεγέθη των αντίστοιχων του screenfetch.

Για τις πληροφορίες εδώ είμαστε να μας στείλετε προτάσεις να κάνουμε/κάνετε
implement.

**Comment by arvchristos** [comment]
@billniakas Απο όσο είδα είσαι σε ubuntu οπότε μπορείς, αφού κατεβάσεις τις τελευταίες αλλαγές του repo να τρέξεις το script και να σου εμφανιστεί το ubuntu logo. Αν έχεις κάτι άλλο να προσθέσεις γράψε εδώ αλλιώς κλέινουμε το issue χαρούμενοι. :)

![ububntu_aslfetch](https://user-images.githubusercontent.com/1295367/61649809-d7725680-acba-11e9-858e-27f0706c4ac3.png)

**Comment by billniakas** [comment]
Δε θα έπρεπε να φαίνεται κατευθείαν χωρίς να δώσω παραμέτρους;

![Στιγμιότυπο από 2019-07-23 09-53-54](https://user-images.githubusercontent.com/12209936/61689430-d7606e00-ad2f-11e9-9f01-87016a2d50d0.png)

**Comment by arvchristos** [comment]
Θα έπρεπε, αν το είχαμε υλοποιήσει

**Comment by billniakas** [comment]
Επιπλέον μπορείτε αν θέλετε να φτιάξετε λίγο την απεικόνιση του επεξεργαστή να μη φαίνονται τα μεγάλα κενά.

**Comment by arvchristos** [comment]
> Επιπλέον μπορείτε αν θέλετε να φτιάξετε λίγο την απεικόνιση του επεξεργαστή να μη φαίνονται τα μεγάλα κενά.

Μπορείς να συμπεριλάβεις σε ένα reply εδώ την έξοδο της ακόλουθης εντολής;
`cat /proc/cpuinfo`

*Το καινούριο issue μεταφέρθηκε για λόγους οργάνωσης των commits σε νέο thread*

**Comment by arvchristos** [comment]
Η συζήτηση μεταφέρεται στο issue #3

**Comment by arvchristos** [comment]
Έτοιμο το fix
